### ISSUE TITLE
Opencv

### ISSUE THREAD

**Issue by HarryOC493** [neurolabusc/AppleSiliconForNeuroimaging#2]
Hi I read that this repository shows which modules work on the new m1 chip, I have been having a ton of issues installing opencv-python inside my Conda venv. but I found a solution so I just wanted to put the following command here in case you want to add it:
`conda install -c menpo opencv`

**Comment by neurolabusc** [comment]
I noted this in passing, but did not evaluate these functions. My sense is that this may be using translated code, which is functional but not optimal. I do think this issue goes beyond the scope of this repository.

There is a niche for a description of modules that support the M1 and how one installs modules on this architecture. However, that topic is outside my expertise.
