### ISSUE TITLE
Docker now runs natively on Apple Silicon

### ISSUE THREAD

**Issue by hickst** [neurolabusc/AppleSiliconForNeuroimaging#4]
"Docker, a popular multi-platform application used by software developers, has released a version that runs natively on Apple Silicon hardware, including Macs released with Apple's custom-designed M1 chip."

From this article: https://arstechnica.com/gadgets/2021/04/popular-software-development-tool-docker-gets-apple-m1-support/

**Comment by neurolabusc** [comment]
Thanks for letting me know. I have updated the page. This is very impressive progress. It looks like there are still [some caveats](https://docs.docker.com/docker-for-mac/apple-silicon/):

 - Some binaries are still Darwin/AMD64
 - Attempts to run Intel-based containers on Apple Silicon machines can crash as QEMU sometimes fails to run the container

**Comment by hickst** [comment]
You're welcome. Thanks for this very nice resource identifying the issues: I think you're "spot on" with many of these.

I've been using Apple for software development since 2005 but Apple seems to be less and less interested in supporting developers. Luckily re-purposing old Apple hardware with Ubuntu 20 seems to work very well.
