### ISSUE TITLE
MeVisLab updates

### ISSUE THREAD

**Issue by teddphil** [neurolabusc/AppleSiliconForNeuroimaging#7]
Hi,
I was trying to install MeVisLab on my M2 laptop and unfortunately found it unsupported unless with Rosetta. I think the information could be useful for other users. May I know where I can contribute it to this forum? Thanks.
Best wishes
teddy

**Comment by neurolabusc** [comment]
Sorry, outside my expertise. I suggest you [contact them](https://www.mevislab.de/contact)
