### ISSUE TITLE
Julia natively supports Apple ARM and generic ARM 

### ISSUE THREAD

**Issue by pdlloyd** [neurolabusc/AppleSiliconForNeuroimaging#8]
From their [downloads](https://julialang.org/downloads/) page, Julia is now distributed on Apple ARM as well as generic ARM for Linux, amongst others.

- Windows (64-bit [native, portable]) (32-bit [native, portable])
- macOS x86 (Intel or Rosetta) (64-bit [.dmg, .tar.gz])
- macOS (Apple Silicon) (64-bit [.dmg, .tar.gz])
- Generic Linux on x86 (64-bit [glibc, musl]), 32-bit)
- Generic Linux on ARM 64-bit (AArch64)
- Generic Linux on PowerPC (64-bit [little endian]) 	
- Generic FreeBSD on x86 (64-bit)

**Comment by neurolabusc** [comment]
Duly noted. As stated in the opening paragraph, much of the software ecosystem is now supported, and this repository is not tracking all the developments. However, the broader view of the potential for this architecture remains timely.
